export const REWARD_LABELS: Readonly<Record<string, string>> = {
  "hub.supply.tutorial": "中心 · 增幅仪教学",
  "a.supply.maze01": "A 区 · 记忆迷宫 01",
  "a.supply.maze03": "A 区 · 记忆迷宫 03",
  "a.supply.firewall.inner": "A 区 · 防火墙内层",
  "a.supply.firewall.deep": "A 区 · 防火墙深层",
  "a.supply.firewall.core": "A 区 · 防火墙核心",
  "a.supply.revisit": "A 区 · 权限回访",
  "b.supply.line01": "B 区 · 一笔画 01",
  "b.supply.line02": "B 区 · 一笔画 02",
  "b.supply.antivirus.light": "B 区 · 轻度杀毒",
  "b.supply.antivirus.medium": "B 区 · 中度杀毒",
  "b.supply.antivirus.heavy": "B 区 · 重度杀毒",
  "b.supply.revisit": "B 区 · 权限回访",
  "c.supply.route.entry": "C 区 · 组合机关入口支路",
  "c.supply.route.exit": "C 区 · 组合机关出口支路",
  "c.supply.theft01": "C 区 · 数据盗取 01",
  "c.supply.theft02": "C 区 · 数据盗取 02",
  "c.supply.theft03": "C 区 · 数据盗取 03",
  "c.supply.side": "C 区 · 侧路终端",
  "d.supply.permission01": "D 区 · 权限 01",
  "d.supply.permission02": "D 区 · 权限 02",
  "d.supply.permission03": "D 区 · 权限 03",
  "d.supply.permission04": "D 区 · 权限 04",
  "d.supply.hidden": "D 区 · 隐藏数据支路",
  "d.supply.ghosts": "D 区 · 两段幽灵通道",
  "hub.supply.final": "中央仓库 · 最终结算",
};
